spring.application.name=ConfigServer
server.port= 8080
#Use local file system
##Enable file system for backend
#spring.profiles.active= native
##Path to configuration files
#spring.cloud.config.server.native.search-locations=file:///C:/Data/config-repo

# Use Git Repository
#Enable file system for backend
spring.cloud.config.server.git.uri=https://github.com/leodevse/ServerConfig
# Ho?c remote: spring.cloud.config.server.git.uri=https://github.com/leodevse/config-repo
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true